<form action="User/Index/Login">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <div class="form-group col-xs-10">
                    <input type="email" class="form-control" name="Email" aria-describedby="emailHelp"
                           placeholder="Email">
                    </small>
                </div>
                <div class="form-group col-xs-10">
                    <input type="Password" class="form-control" name="Password" aria-describedby="emailHelp"
                           placeholder="Password">
                    </small>
                </div>
                <div class="form-group col-xs-10">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <div class="form-group col-xs-10">
                    <small><?=$Message;?></small>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6">Don't have an account? <a href="<?= Application::getURL("User/Index/Register"); ?>">Register</a>
            </div>
        </div>
    </div>
    <script>
        refresh("#top");
    </script>
</form>