<html>
<head>
    <title><?= $Layout->getTitle(); ?></title>
    <style>
        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        body {
            margin: 0;
            color: #ffffff;
            font-family: arial;
        }

        body, div {
            display: flex;
            flex-wrap: wrap;
        }

        #center {
            width: 60%;
        }

        #top, #bottom {
            background: #333333;
            width: 100%;
            height: 10%;
        }

        #left, #right {
            width: 20%;
            background: #444444;
            padding: 1em;
            background: #444444;
            border: 1em #333333;
        }

        #left, #center, #right {
            height: 80%;
        }

        #Navigation {
            margin: auto;
            width: 20%;
            align-content: center;
            justify-content: space-around;
        }

        #Navigation I {
            background: #444444;
        }

        #copyright {
            width: 100%;
            height: 100%;
            align-items: center;
            justify-content: center;;
        }

        #Search {
            align-items: center;
            justify-content: center;
            margin: auto;
            width: 60%;
        }

        form {
            margin: 0;
        }

        #Logo {
            align-items: center;
            justify-content: center;
            width: 20%;
        }

        .box {
            width: 100%;
            display: initial;
        }

        .box .title {
            width: 100%;
        }

        .column {
            overflow: auto;
        }

        #Search form {
            display: flex;
            align-items: center;
        }

        #Search i {
            padding-left: 1em;
        }

        #center {
            color: #1b1b1b;
        }
    </style>
    <link rel="stylesheet" href="<?= BASE ?>Application.css">
    <script src="https://use.fontawesome.com/49642d2436.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="Application/Module/Layout/Template/Layout.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</head>
<body>
<div id="top" class="row" src="Layout/Top">
</div>
<div id="left" class="column">
    <div class="box">
        <div class="title">Title</div>
        <div class="content">Content</div>
    </div>
</div>
<div id="center" class="column">
    Center
</div>
<div id="right" src="<?= BASE ?>User/Info" class="column"></div>
<div id="bottom" src="<?= BASE ?>Layout/Bottom">
    <div id="copyright">&copy; Andy Noblet 2016</div>
</div>
<script type="text/javascript" src="http://localhost:8080/s/53a6b67871465ed7b4838db208cf960f-T/-6pq3en/74002/b6b48b2829824b869586ac216d119363/2.0.23/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=a76297e0"></script>
</body>
</html>
