<div id="Logo"><a href="<?= $this->getURL(); ?>">Andy Noblet</a></div>
<div id="Search">
    <form>
        <input type="text" name="Search"/>
        <label for="Search">
            <i class="fa fa-fw fa-search" aria-hidden="true"></i>
        </label>
    </form>
</div>
<div id="Navigation" src="Layout/Navigation">
    <select>
        <option selected hidden>My Account</option>
        <option value="User/Login">Sign In / Register</option>
    </select>
</div>