<html>
<head>
    <title><?= $this->getTitle(); ?></title>
    <style>
        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        body {
            margin: 0;
            color: #ffffff;
            font-family: arial;
        }

        body, div {
            display: flex;
            flex-wrap: wrap;
        }

        #center {
            width: 60%;
        }

        #top, #bottom {
            background: #1b1b1b;
            width: 100%;
            height: 10%;
        }

        #left, #right {
            width: 20%;
            background: #1b1b1b;
            padding: 1em;
        }

        #left, #center, #right {
            height: 80%;
        }

        .scroll {
            overflow: auto;
        }

        #Navigation {
            margin: auto;
            width: 20%;
        }

        #copyright {
            width: 100%;
            height: 100%;
            align-items: center;
            justify-content: center;;
        }

        #Search {
            align-items: center;
            margin: auto;
            width: 60%;
        }

        form {
            margin: 0;
        }

        #Logo {
            align-items: center;
            justify-content: center;
            width: 20%;
        }
    </style>
    <script src="https://use.fontawesome.com/49642d2436.js"></script>
</head>
<body>
<div id="top" class="row">
    <div id="Logo">Andy Noblet</div>
    <div id="Search">
        <form>
            <label for="Search">
                <i class="fa fa-fw fa-search" aria-hidden="true"></i>
            </label>
            , <input type="text" name="Search"/>
        </form>
    </div>
    <div id="Navigation">
        <i class="fa fa-cog" aria-hidden="true"></i>
    </div>
</div>
<div id="left" class="column">Left</div>
<div id="center" class="column">
    <div class="content">
        <div class="scroll">Center</div>
    </div>
</div>
<div id="right">Right</div>
<div id="bottom">
    <div id="copyright">&copy; Andy Noblet 2016</div>
</div>
</body>
</html>
