<form action="User/Index/Register">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group col-xs-10">
                    <input type="email" class="form-control" name="Email" aria-describedby="emailHelp"
                           placeholder="Email">
                    </small>
                </div>
                <div class="form-group col-xs-10">
                    <input type="Password" class="form-control" name="Password" aria-describedby="emailHelp"
                           placeholder="Password">
                </div>
                <div class="form-group col-xs-10">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
                <div class="form-group col-xs-10">
                    <small><?=$Message;?></small>
                </div>
            </div>
            <div class="col-xs-6"> Have an account? <a href="<?= Application::getURL("User/Index/Login"); ?>">Login</a>
            </div>
        </div>
    </div>
    <script>
       load("#Navigation");
    </script>
</form>