<form action="<?= BASE ?>User/Index/Login" method="POST">
    <div class="form-group">
        <label for="Email">Email: </label>
        <input type="text" name="Email" value="<?= $User->Email; ?>" class="form-control"/></div>
    <div class="form-group">
        <label for="Password">Password: </label>
        <input type="password" name="Password" value="<?= $User->Password; ?>" class="form-control"/>
    </div>
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-1">
            <button type="submit" class="btn btn-primary">Register</button>
        </div>
    </div>
    <div class="form-group row">
        Have an account? <a href="<?= Application::getURL("User/Index/Login"); ?>">Login</a>
    </div>
</form>
<script>
    refresh("#top");
</script>
