<form action="<?= BASE ?>User/Index/Login" method="POST">
    <div class="container-fluid">
        <div class="form-group row">
            <div class="col-md-12">
                <label for="Email">Email: </label>
                <input type="text" name="Email" value="<?= $User->Email; ?>" class="form-control"/>
            </div>
        </div>
        <div class="form-group row">
            <label for="Password">Password: </label>
            <div class="col-sm-12">
                <input type="password" name="Password" value="<?= $User->Password; ?>" class="form-control"/>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-sm-2 col-sm-1">
                <button type="submit" class="btn btn-primary">Register</button>
            </div>
        </div>
        <div class="form-group row">
            Don't have an account? <a href="<?= Application::getURL("User/Index/Register"); ?>">Register</a>
        </div>
    </div>
    <script>
        refresh("#top");
    </script>
</form>

